volumes:
  local_xdel_postgres_data: {}
  local_xdel_postgres_data_backups: {}

services:
  flask:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: xdel_api_local
    container_name: xdel_api_local
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.flask.env
      - ./.envs/.local/.postgres.env
    ports:
      - "5000:5000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: xdel_api_postgres_local
    container_name: xdel_api_postgres_local
    volumes:
      - local_xdel_postgres_data:/var/lib/postgresql/data
      - local_xdel_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres.env
    ports:
      - "5432:5432"